### ISSUE TITLE
Create interactive skeuomorphic map for Cohere+

### ISSUE THREAD

**Issue by catherinet1** [life-itself/second-renaissance#319] opened 2024-06-07 19:40 UTC
## Acceptance

- [x] All 300 organisations in Cohere+ directory plotted on map
  - [x] All 300 organisations assigned a territory
  - [x] Coordinates for all 300 organisations 
- [x]  Interactive map live on secondrenaissance.net/cohere/map **Searchable map with 300 organisations from Cohere+ directory plotted on it is live: https://secondrenaissance.net/ecosystem/cohere/map. Clicking on a point on the map displays the organisation name, beginning of description, image, and link to full profile in directory. This info is pulled from Cohere+ database.**

### Testing and shaping **⏰ ~1d**

- [x] Test https://azgaar.github.io/Fantasy-Map-Generator/ **Seems like easy-to-use tool with good functionality. See questions and notes below. Main q not yet answered is how do we share/publish the map we create??**
- [x] Pull out list of all orgs and map territories and review, e.g. for ones which are populated very much or very little (to help decide what edits to make to territories) **See Map tab in https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit?gid=340574560#gid=340574560 and table counting occurrences of territories (also in screenshot in comments)**

### Iterate map design **⏰ ~3-5d**

- [x] Finalise design of map baselayer (territories) based on Matt's version **Map base image is saved as .map, svg and png in this folder: https://drive.google.com/drive/folders/12fuNedkMtuotMDzza-EGXWBozhklcTDy. See image below.**
  - [x] Sketch **See sketches in https://excalidraw.com/#room=c373f9b9a59128681b98,1gGW7m3dnNmdMQHdhqxj9A**
  - [x] Draw in Azgaar **Saved final map base image as .map (can load into Azgaar and edit using this format) svg and png in https://drive.google.com/drive/folders/12fuNedkMtuotMDzza-EGXWBozhklcTDy**
![Image](https://github.com/user-attachments/assets/0cb15fd9-0546-4ac7-b214-0b84e2465b5d)
- [x] Assign territory to every org **Done in Map Master tab in https://docs.google.com/spreadsheets/d/1VbMvdy_pPzdREsAsXxONZWbPWS0rLxsy-NWJCg1cYDw/edit?gid=2142115581#gid=2142115581. Some have question marks. Can assign when plotting orgs.**

### Building map

- [x] Technical build
- [x] Plot each organisation on the map (and add label and link to profile etc.) **⏰ 0.5d**

### Testing Azgaar

  - [x] Can we add 300 organisation points? Will it look too crowded? **🔑 I think it is fine. This is what test looks like with 23 points in Metamodern territory. In Azgaar we can adjust territories to be a bit bigger or smaller to fit in points.**
![Image](https://github.com/user-attachments/assets/4fca2c72-b878-4251-ba91-6b68ff4f4e39)
  - [x] What will the display of one organisation look like? **🔑 When you hover over a marker, its title and any free text notes will show up in a box in the top right-hand corner (see screenshot example)** 
 ![Image](https://github.com/user-attachments/assets/e3023ec4-665f-43e0-8172-e45a4831b096)
  - [x] Can we link to profile page? **🔑 Yes, add link to free text notes for marker**
  - [ ] How long does it take to plot each organisation and fill in relevant info, e.g. link to profile?
  - [x] How easy is it to replot or remove or add organisations? **🔑 Easy: you can drag and drop markers. Also delete and add.**
  - [ ] How do you publish map/share map with others?

#### Notes on using Azgaar

- The way to get around the every state must have a capital burg thing is to make the burg style totally transparent and delete the burg's name, that way neither the burg nor its label will appear on the map.
- To move markers, zoom in, click on the marker and hover until you see the 4-point icon. Then drag and drop.
- Azgaar's Fantasy Map Tutorial 1: Basics and creating your own map,  https://www.youtube.com/watch?v=6MFiHXAVUUY

### Possibilities/Purpose of this map Brainstorm

Catherine
- Kind of like a treasure map, more than a systematic overview... 
- A tool for **inspiring** 
- Gives a sense that there is this lively, thriving, bustling world of inspiring social change initiatives out there
- Dive in and see what **opportunities** you discover
- Sense of concrete possibility
- Supporting concrete action because people can find live events and groups they can join etc. and real organisations and projects that they can contribute to - **connecting** people to projects and initiatives
- Sense of fun/playfulness due to style of map helps to bring the data alive 
- From the map as a whole...get an **overview of breadth of activity**, sense of scale of movement? 
- Possibility of people contributing to the map or adding to it? Invites engagement around imagining where you fit in, how different activities and organisations you know fit together?
- Inspiring hope - seeing how many people across so many different activities are united by this approach/vision of deep systems change

Elisa
- Providing a sense of the diversity within the ecosystem
- Visual aid helps people remember things better (different aspects of the eosystem; what different orgs are about / how they relate to each other)
- In highlighting differences, it also highlights the similarities (what connects them / why are they on the same map?)
- Creates a sense that there is an ecosystem out there that is real and definable
- Introduces people to key concepts within the ecosystem (metacrisis, integral, etc.) - and can **stimulate discussion** on how they relate
- **Helps people find others** who are doing interesting work in their areas of interest

How might people use this map?
- Sending to others already in the space to geek out and have fun with it. Seeing connections and links and questioning whether I agree with it etc. Trying to understanding the concepts within the ecosystem -- sensemaking and understanding the ecosystem better
- Sending it to others who are not so familiar e.g. you meet someone at a conference who doesn't know what "this space" is - **a visual introduction to "this space"**
- Accessible entry point for someone new to the space to explore 
- Intro text is an abstraction whereas this is less abstract, more tangible, what are the component parts on the ground? (or abstract framework of map combined with tangibleness of real examples)
- People can dip in and out easily, explore as much or as little as they like

**Comment by rufuspollock** [comment] 2024-06-30 10:37
@catherinet1 is this for cohere+ or for existing map?

If existing map then this is duplicate of #311 i think. If former can we rename to make that clear ...

**Comment by catherinet1** [comment] 2024-08-11 11:12
Screenshot showing occurrence of map territories with roughly 200/300 organisations having been categorised:

![Image](https://github.com/user-attachments/assets/136e1482-3e42-469f-8e15-a60e92864972)

**Comment by catherinet1** [comment] 2024-10-07 10:53
FIXED. Searchable map with 300 organisations from Cohere+ directory plotted on it is live: https://secondrenaissance.net/ecosystem/cohere/map. Clicking on a point on the map displays the organisation name, beginning of description, image, and link to full profile in directory. This info is pulled from Cohere+ database.

**Closed** 2024-10-07 10:54 UTC
Labels: Area: Visualization, Area: Cohere
